### PR TITLE
Shorter wait

### PR DESCRIPTION
**Pull request by michalc**

### CODE REVIEW

**Comment by michalc** [comment]
Incorrect repo again...

**Comment by mikecann** [comment]
👍  no wories

**Comment by mikecann** [comment]
@michalc do you mind me asking actually, what are you building with it?

**Comment by michalc** [comment]
@mikecann Sure! I was changing/(hacking?) it a bit to crawl a site and, instead of showing interesting files, showing cookies. (Latest version now at https://github.com/michalc/Chrome-Crawler )

**Comment by mikecann** [comment]
Cool :) thanks :)

*Mike Cann*
http://www.mikecann.co.uk/
@mikeysee <http://www.twitter.com/mikeysee>

**Pull request closed without merging**
